### PR TITLE
Create leaderboard layout

### PR DESCRIPTION
**Pull request by Taktakomar**

### CODE REVIEW

**Review by mbachmann97 — APPROVED** [review]
Looks good to me. We should probably look for a standard design for all our windows

**Review by Maximania1444 — APPROVED** [review]
Das schaut gut aus.

**Review by PatrickJung94 — APPROVED** [review]
Looks good. Unused code can be removed later. See `MenuWindow.java` Line 139

**Review by mbachmann97 — APPROVED** [review]
Looks good. Commented code should be removed in the future f.e. `HighscorePopup.java` line 53

**Review by Maximania1444 — APPROVED** [review]
Schaut gut aus.

**Pull request merged**
